Fixed a failing test.
We were getting this error when using #scoped:

    ArgumentError: wrong number of arguments (1 for 0)

Given that we're only checking the return values (and don't need to use the scope object itself) I think it's good enough to change #scoped to #all.